# name: GitHub Actions
# on: 
  # push:
    # branches: [ develop ]
  # pull_request:
    # branches: [ master ]
# jobs:
#   init:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [ 18.x ]
#     steps:
#       - uses: actions/checkout@v3
#       - name: Starting Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with: 
#           node-version: ${{ matrix.node-version}}
      # - name: install modules
      #   run: npm install 
      # - name: build project
      #   run: npm run build
      
